<!DOCTYPE html>
<html>
<head>
    <title>Contact List</title>
</head>
<body>
    <h1 class="text-center">Contact List</h1>
    <a href="?page=contact_add" class="btn btn-primary m-1">Add Contact</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Firstname</th>
                <th scope="col">Email</th>
                <th scope="col">Password</th>
                <th scope="col">PasswordConf</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($users as $user) : ?>
            <tr>
                <th scope="row"><?= $user['id'] ?></th>
                <td><?= $user['name'] ?></td>
                <td><?= $user['firstname'] ?></td>
                <td><?= $user['email'] ?></td>
                <td><?= $user['password'] ?></td>
                <td><?= $user['passwordconf'] ?></td>
                <td>
                    <a href="?page=contact_update&id=<?= $user['id'] ?>" class="btn btn-success m-1">Update</a>
                    <a href="?page=contact_delete&id=<?= $user['id'] ?>" class="btn btn-danger m-1">Delete</a>
                    <a href="javascript:deleteUsers(<?= $user['id'] ?>)" class="btn btn-warning m-1">Delete? (confirmJS)</a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
    <script>
        function deleteUsers(id) {
            const question = window.confirm("Are you sure you want to delete " + id + " ?");
            if (question) {
                location.href = "?page=contact_delete&Id=" + id;
            }
        }
    </script>
    <a href="?page=contact_add" class="btn btn-primary m-1">Add Contact</a>
</body>
</html>