<h1 class="text-center">Contact Update User</h1>
    <p class="text-center">Veuillez compléter le formulaire ci-dessous pour créer votre espace personnel.</p>

    <div class="form">
        <form id="subscribe" method="POST">
            <label for="name">Nom :</label>
            <input type="text" name="name" id="name" placeholder="Nom">
            
            <label for="firstName">Prénom :</label>
            <input type="text" name="firstName" id="firstName"  placeholder="Prénom">

            <label for="mail">Email :</label>
            <input type="mail" name="mail" id="mail" placeholder="Email">
            
            <label for="password">Mot de passe* :</label>
            <span>(*12 characters minimum)</span>
            <input type="password" id="password" name="password" placeholder="Mot de passe">

            <label for="passwordConf">Confirmation du mot de passe* :</label>
            <span>(* Identique au Mot de passe)</span>
            <input type="password" id="passwordConf" name="passwordConf" placeholder="Confirmer le mot de passe">

            <input type="submit" class="btn btn-primary" name="submit" value="Add Contact">
        </form>
    </div>
