<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>

    <style>
        div {
            display: flex;
            justify-content: center;
        }

        p {
            color: grey;
        }

        input {
            padding: 5px;
            display: flex;
            border-radius: 5px;
            width: 350px;
        }

        label {
            display: block;
        }

        input[type='submit'],
        label {
            margin-top: 1rem;
            border-radius: 5px;
        }
    </style>
</head>

<body>
    <h1 class="mb-3 text-center">Admin Login</h1>

    <?php if (isset($error_message) && !empty($error_message)) : ?>
        <div class="alert alert-danger">
            <?= $error_message ?>
        </div>
    <?php endif; ?>

    <div class="form">
        <form method="POST">
            <label for="username" class="form-label">Username :</label>
            <input type="text" name="username" id="username" placeholder="Username">

            <label for="password" class="form-label">Password :</label>
            <input type="password" name="password" id="password" placeholder="Password">

            <input type="submit" class="btn btn-primary" name="submit" value="Login">
        </form>
    </div>

</body>
</html>