<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact</title>

    <style>
    div{
        display: flex;
        justify-content: center;
    }
    p{
        color: grey;
    }
    input{
        padding: 5px;
        display: flex;
        border-radius: 5px;
        width:350px;
    }
    label {
        display: block;
    }

    input[type='submit'], label {
    margin-top: 1rem;
    border-radius: 5px;
    }

    span{
        font-size: xx-small;
        color: grey;
    }
    </style>

</head>

<body>

    <h1 class="mb-3 text-center">Contact</h1>
    <p class="text-center">Veuillez compléter le formulaire ci-dessous pour créer votre espace personnel.</p>

    <div class="form">
        <form  method="POST">
            <label for="name" class="form-label">Nom :</label>
            <input type="text" name="name" id="name" placeholder="Nom">
        
            <label for="firstName" class="form-label">Prénom :</label>
            <input type="text" name="firstname" id="firstname"  placeholder="Prénom">
        
        
            <label for="mail" class="form-label">Email :</label>
            <input type="mail" name="mail" id="mail" placeholder="Email">
        
            <label for="password" class="form-label">Mot de passe* :</label>
            <span>(*12 characters minimum)</span>
            <input type="password" id="pass" name="password" placeholder="Mot de passe">
        
            <label for="passwordConf" class="form-label">Confirmation du mot de passe* :</label>
            <span>(* Identique au Mot de passe)</span>
            <input type="password" id="passwordConf" name="passwordConf" placeholder="Confirmer le mot de passe">
        
            <input type="submit" class="btn btn-primary" name="submit" value="Add Contact">
        </form>
    </div>

</body>
</html>
